### ISSUE TITLE
The playhead and repeat markers should appear on the panel screen

### ISSUE THREAD

**Issue by RichieHindle** [EntrianAudio/Rack#1]
In order to move the playhead, or to set repeat markers, you currently have to show the editor.  Those controls should appear on the panel screen so you can manipulate them directly without needing to launch the editor.

Similarly, you should be able to arm a track for recording by clicking its label on the panel screen.

**Comment by RichieHindle** [comment]
More from Artem on the idea of arming tracks from the panel:

"I think we need something on track arming at the front panel for better, faster and intuitive recording. Something like knob for choosing needed track and another knob or menu for defining track type (just because we can’t record anything now without making a clear clip to define the track type). This will allow us to do some live looping stuff, sketching and other useful things! It would be so awesome if could add it in the future Richie (or expander of course if you don’t have enough room anymore at the front panel)."

Clicking the name of a track on the panel screen in order to arm that track for recording would achieve the first part, but would still require a blank clip to record into.  To implement the idea completely, arming a track and starting to record into an empty space within it would need to create a clip (presumably filling all the space at the current playhead).  There would need to be something that decided on the clip type to create; maybe an explicit option in the editor, or deriving the clip type from other clips in the track, or the last clip type to be present in the track it was empty, or the last clip type to be recorded into...?

**Comment by RichieHindle** [comment]
In version 1.1.16, clicking a Timeline track label on the panel screen now arms that track for recording.

**Comment by EntrianAudio** [comment]
Implemented in version 1.1.17.  You still need to create a clip to record into; clips won't be created as a side-effect of recording.
