### ISSUE TITLE
Piano roll does not line up exactly to the piano notes.

### ISSUE THREAD

**Issue by EntrianAudio** [EntrianAudio/Rack#13]
The paino note grid behind a Melody clip, and the piano guide down the left-hand side, don't always line up properly.  This is most noticeable when the editor is vertically scrolled so that the top two white notes have no black note (so B/C or E/F).

(Bug report by forum member Coirt.)

**Comment by RichieHindle** [comment]
Fixed in version 1.1.6 - thanks, @Coirt.
