### ISSUE TITLE
There should be a single gesture to reset a scrollbar

### ISSUE THREAD

**Issue by RichieHindle** [EntrianAudio/Rack#2]
Resetting a scrollbar takes two move-drag gestures, one for each end of the scrollbar, each a long way from the other.  There should be a quicker way to do it, probably a right-click.

**Comment by Coirt** [comment]
I'd probably say double click here rather than right-click. In continuity with Rack's param reset.

**Comment by RichieHindle** [comment]
Implemented in version 1.1.16, as right-click.
