### ISSUE TITLE
Run / Reset buttons in the editor

### ISSUE THREAD

**Issue by EntrianAudio** [EntrianAudio/Rack#22]
Run and Reset buttons in the editor would be really useful.  In order to cooperate with an external clock, they might have to go to outputs on the panel.

(Suggestion from forum user Eurikon.)

**Comment by RichieHindle** [comment]
Eurikon's mockup:
![image](https://user-images.githubusercontent.com/4448057/76691856-687daf80-6647-11ea-9f55-e51f347c75a5.png)

**Comment by RichieHindle** [comment]
...and a similar mockup from Artem:

![image](https://user-images.githubusercontent.com/4448057/76691871-83e8ba80-6647-11ea-8cdd-09cc912c531a.png)

This has "Play", "Play from start", "Stop", and "Loop on/off" (so you can conveniently see that with the other controls).

**Comment by EntrianAudio** [comment]
Implemented in version 1.1.17.
