### ISSUE TITLE
"End of song" output

### ISSUE THREAD

**Issue by EntrianAudio** [EntrianAudio/Rack#31]
An output trigger for "End of song" would be useful.

(Suggestions from forum user Jue.)

(See also #22, which suggests Run and Reset outputs.)

**Comment by EntrianAudio** [comment]
Further to this, to work with more granularity, and end-of-clip output per-track would be useful.

**Comment by ContemporaryInsanity** [comment]
Could we also have an end of phrase out on Drummer & Melody too please?

**Comment by EntrianAudio** [comment]
Implemented in version 1.1.17.
