### ISSUE TITLE
Mouse disappears if a module control is altered while editor window open (linux).

### ISSUE THREAD

**Issue by ContemporaryInsanity** [EntrianAudio/Rack#32]
Hi Richie.

Firstly, fantastic work, thanks!

If I have an Entrian editor window open and I move a control on any module, my mouse pointer disappears, the control clicked on then retains focus even after releasing the mouse button, i.e. moving the mouse will still move the control.  I can work around this by hitting the system menu key which then restores the mouse pointer when VCV loses focus.  Alt-tab also restores the pointer.  FYI this is on a multi monitor system.

Cheers!

E.

**Comment by RichieHindle** [comment]
Ouch!  That's not good.  Could you let me know anything that I need to know to try to reproduce the problem?:

* What operating system you're using
* What version the operating system is
* What version of Rack you're using
* Whether and how the behaviour changes with how you arrange your windows across your monitors
* Anything else that might be relevant.

As you can probably tell, I haven't seen this before, but I'd very much like to fix it!

**Comment by ContemporaryInsanity** [comment]
Ok, this is odd, it now appears to be working fine, also, the editor windows are resizable now, they weren't yesterday, haven't rebooted or anything like that, only restarted rack.  Oh well, if it happens again I'll let you know.

**Comment by RichieHindle** [comment]
Bizarre!  Thanks for letting me know.

**Comment by ContemporaryInsanity** [comment]
This is still happening on occasion, when it does the editor windows won't resize.  I can't replicate this consistently yet, if I find a way I'll let you know.
