### ISSUE TITLE
Melody channels colour coded

### ISSUE THREAD

**Issue by Coirt** [EntrianAudio/Rack#33]
would be nice to have different colours for assigned channels to quickly see what channels are what...

![colorCode](https://user-images.githubusercontent.com/12150421/76325629-721db500-62df-11ea-9223-f82110a67a74.PNG)

**Comment by RichieHindle** [comment]
Implemented in version 1.1.16 - thanks for the suggestion!

![image](https://user-images.githubusercontent.com/4448057/85365200-c52d1800-b51c-11ea-9dfb-ed7ee54c819e.png)
