### ISSUE TITLE
Melody (and Drummer): add a button or CV input to clear the sequence.

### ISSUE THREAD

**Issue by jsmonzani** [EntrianAudio/Rack#34]
I would love a CV or a button to clear the sequence, as I like to record /play my sequences live.

**Comment by RichieHindle** [comment]
There's a "Delete all notes" button in the editor, but are you specifically asking for one on the panel?

**Comment by jsmonzani** [comment]
Yes, I'm referring to one input / button in the panel for external control of notes deleting by CV, without having to open the editor window.

I would love to externally control  the editor window but I don't think that's possible yet. For example, using uMap to control the editor window buttons as they are not standard VCV mappable controls, if I'm not mistaken? I can't try this right now. Thank you

**Comment by jsmonzani** [comment]
I've tried to "automate" the "Clear notes" button from the editor and can confirm that it's not a standard VCV control, and that this fails.
So yeah, I'd definitively love a button on the panel, please :) Thank you!

**Comment by ContemporaryInsanity** [comment]
I would appreciate this too, as is I need to have an editor window open with the mouse hovering over delete all notes, would be great to be able to map a controller button to this function.

**Comment by ContemporaryInsanity** [comment]
Here's how I'm currently attempting to use Melody.  I have a separate midi keyboard routed into each instance of Melody via a switch to switch between playing notes and selecting phrases with the keyboards.  I have four buttons on my X-Touch mini mapped so I can switch each instance of Melody between playing / recording and phrase selection.  With this setup, I can record, play & select phrases from either row without going near PC keyboard or mouse.  Great so far, however to zap a phrase and start from scratch I need to open an editor window and use the mouse, same if I want to quantize recorded notes, this is why I'd like the option to erase the current phrase via a panel input or mappable button, being able to quantize a phrase this way too would also be useful, or perhaps a switchable auto-quantize option could be even better, not sure.  Hope this provides some insight and thanks once more for the great modules.

![EntrianUseCase](https://user-images.githubusercontent.com/12547379/76976091-62c7e880-692b-11ea-88df-d923828d9245.png)

**Comment by RichieHindle** [comment]
Thanks Ewen, that's a really useful insight into how you're using the modules!

**Comment by jsmonzani** [comment]
Great insight! I'm using a similar setup idea, so I see why we're sharing the same need!

**Comment by ContemporaryInsanity** [comment]
What are your thoughts on quantization?  Having considered it further, if we could quantize on demand (button or input), if we wanted auto-quantize we could route the clock to quantize on demand?

**Comment by EntrianAudio** [comment]
We already have auto-quantize - that's what the "Quantization?" checkbox in the editor does.  Do you need to switch that on and off during a performance?

**Comment by ContemporaryInsanity** [comment]
That only appears to apply to notes placed on the grid via mouse, it doesn't quantize notes recorded via the inputs.

**Comment by RichieHindle** [comment]
It ought to quantize notes recorded from the inputs... either it's working for me or I'm the world's most accurate QWERTY-keyboardist.  :-)

![image](https://user-images.githubusercontent.com/4448057/77228767-7e2c3100-6b81-11ea-8df8-73d8730fcc3e.png)

**Comment by ContemporaryInsanity** [comment]
Here it ignores steps per beat until you hit quantize all notes.  This is in Melody but appears the same in Timeline.

Before hitting quantize:

![image](https://user-images.githubusercontent.com/12547379/77229059-5e960800-6b83-11ea-8dd6-dc5f71892420.png)

After hitting quantize:

![image](https://user-images.githubusercontent.com/12547379/77229066-69e93380-6b83-11ea-8ff2-893fedd59979.png)

Not a huge issue really, being able to clear a phrase without using the mouse is by far more important I think, for me at least, but this would be handy.

PS.  Cursor still disappears and editor windows refuse to resize thereafter, seems to be to do with having multiple editor windows open but still can't reliably recreate, thankfully not a show stopper.

**Comment by RichieHindle** [comment]
Ah, got it - the note _positions_ are being quantized, but the _lengths_ aren't.

I ummed and ahhed about that as I was writing it, and decided that this was the right thing to do, but I'm open to disagreement on that.  Looking at it now, it does seem like a questionable decision.  🤪

**Comment by ContemporaryInsanity** [comment]
Anything happening with this?  Definitely my #1 want for Entrian (#2 being mod/pitch addition to Melody).  This is what can be so frustrating about paid modules in a largely free system, were it open source I'd have long since done it myself.  Having said that these are interesting times, hope all is well Richie and thx once more for the great (soon to be even greater I hope) modules :)

**Comment by jsmonzani** [comment]
Same here 😊

**Comment by RichieHindle** [comment]
Sorry to go quiet for so long - lots of other things getting in the way (but nothing too "interesting", thankfully).

The next release, due in maybe a week's time, will have a Clear button on the panel (and available for automation) and will quantize recorded note lengths as well as positions.

![image](https://user-images.githubusercontent.com/4448057/83980000-21335200-a90a-11ea-99cf-798d140df7e1.png)

**Comment by jsmonzani** [comment]
This is much appreciated, thank you!

**Comment by EntrianAudio** [comment]
Now in the VCV Library.  😃
