### ISSUE TITLE
Polyphonic CV recording

### ISSUE THREAD

**Issue by EntrianAudio** [EntrianAudio/Rack#39]
You should be able to record multiple CV channels at once, either by individually arming channels or by having an "arm all" / "arm none" UI.

(Suggestion from forum user VCVRackIdeas.)

**Comment by EntrianAudio** [comment]
Here's a related suggestion from Latif:

"In the timeline sequencer it would be useful if when the track editor is opened, selecting multiple channels will show all data of the selected channels combined.

When clicking on data of a specific channel, this data is then active for editing, while still showing all data of all channels."

This is different from recording, but is similar in that it relies on having a way of selecting multiple channels at once.

**Comment by ContemporaryInsanity** [comment]
I'd like to be able to record notes along with pitch & mod wheel data from a midi keyboard, I can get around this for now (sort of, in a limited way) using one of my own modules but would be a nice addition to Entrian.  Bonus points for aftertouch.

**Comment by RichieHindle** [comment]
How do you see that working?  A melody clip for the notes and a simultaneous CV clip for the modulations?  Or recording the whole lot into different channels of a CV clip?

**Comment by ContemporaryInsanity** [comment]
The former I think would make more sense, as note data may be polyphonic but mod/pitch isn't?

**Comment by EntrianAudio** [comment]
We're gonna need a bigger panel.

**Comment by RichieHindle** [comment]
No, not a bigger panel, a whole new module:

![image](https://user-images.githubusercontent.com/4448057/90311385-391ee780-def2-11ea-9982-c8ef4437a87a.png)

(Still a work in progress, but on its way.)

**Comment by ContemporaryInsanity** [comment]
Whoops, we've crossed in the post :)

**Comment by EntrianAudio** [comment]
Implemented in version 1.1.17.
