### ISSUE TITLE
Polyphonic recording sends wrong gates and too many notes when monitoring.

### ISSUE THREAD

**Issue by jsmonzani** [EntrianAudio/Rack#43]
Melody and Timeling sends wrong polyphonic gates on output while recording (i.e. : recorded gates / notes + gates / notes from the timeline).

Please check the included patch.
[https://drive.google.com/file/d/1tkcMsj3mBm69XwVa6bT0x4GrhpUIvjaV/view?usp=sharing](url)

While recording multiple notes, whenever a gate is on/off, it is sent to all hold notes. So it's a problem when recording and monitoring it.

The top Melody is the player. If you listen to the melody, it works fine: C, then E, then G

Now, try to hit Record on the bottom Melody: whenever a note is triggered or released,  ALL other notes are retriggered. You can check the channels and notice that more than 3 channels become active. So you get C, then C+E as if they were hit together, then C+E+G as hit together.

Thank you

**Comment by RichieHindle** [comment]
Thanks for the detailed bug report!  This bug is fixed, and the fix will be in the next release of Entrian Sequencers, due in the next week or so.

**Comment by jsmonzani** [comment]
Wonderful! Thank you!

**Comment by EntrianAudio** [comment]
Now in the VCV Library, version 1.1.16.
