### ISSUE TITLE
Timeline Limits

### ISSUE THREAD

**Issue by knchaffin** [EntrianAudio/Rack#44]
Hello, I have been transcribing Bach's Toccata and Fugue in Dm to the Entrian Timeline sequencer with very good results.  This piece has 140 bars.  Some of my testing seems to show that there is a 128 bar limit in Timeline.  Is this the case?  Since this is a commercial module, I cannot look at the source code and answer this for myself.

By the way, I am using Host with an Arturia V series Hammond B-3 cathedral organ VST as the sound generator.  It sounds amazing.  Bach used a lot of tempo changes, which I duplicate by having a tempo CV track which controls Clocked BPM.  This also works great.

Thank you,
Ken Chaffin

**Comment by RichieHindle** [comment]
There is no limit to the number of bars, but now that I come to try to create a piece with hundreds of bars, I find that there comes a point when the bar lines and numbers stop being displayed.  If you make your editor window wider they come back (up to a point).  You can still edit notes, but obviously that's not easy without the bar lines!

I'll see what I can do to fix that.

(Great to hear you're using a tempo CV track!  It's something I thought people might do, and I tinkered with it myself for testing purposes, but this is the first time someone has told me they're doing it for real!)

**Comment by knchaffin** [comment]
Yes, that is what I saw, the bar lines and numbers quit displaying.  Good to hear there is no bar limit.  I will keep proceeding and see how far I get.  I'm currently up to bar 90.

Thanks for answering my question.  Timeline is a great module!

**Comment by RichieHindle** [comment]
Fixed in version 1.1.16 (which can also paint quantisation lines in the editor, if that's useful to you).
