### ISSUE TITLE
Link multiple sequencer modules together so they share a playhead, for when ten tracks isn't enough

### ISSUE THREAD

**Issue by RichieHindle** [EntrianAudio/Rack#46]
It should be possible to tell an instance of Timeline to take its playhead from another instance, effectively extending that first instance by another ten tracks.

By default, module instances should be independent, but you should be able to nominate one as a "Playhead leader" and any number of others as "Playhead followers", whose playheads will follow the leader's.

Moving the playhead or hitting Reset on any leader/follower module will move or reset the shared playhead.  (It might seem odd that a follower can move the playhead, but why not - the alternative is that it does nothing.  By allowing any of the linked modules to move the playhead, you can control it from the panel or editor of any linked module.)

Switching Run off on a follower will not affect the playhead, but will effectively mute that module.  (This is a case where a difference in behaviour between leader and followers is useful.)

All the linked modules should share the same Clock, Reset, and Run inputs, as they would if you weren't linking them.

**Comment by EntrianAudio** [comment]
Implemented in version 1.1.17.
