### ISSUE TITLE
The CV editor should go from -10V to +10V

### ISSUE THREAD

**Issue by RichieHindle** [EntrianAudio/Rack#47]
The CV editor currently goes from -5V to +10V, because the VCV Voltage Standards document says "CV modulation sources should typically be 0 to 10V (unipolar CV) or ±5V (bipolar CV)."

But it also also says "The only rule is that you can always find a module which breaks the rule" and there are modules that will produce CV signals in the full -10V to +10V range - Vult Caudal is an example.  It should be possible to record and edit the full range.

(Issue broken out from #40.)

**Comment by EntrianAudio** [comment]
Implemented in version 1.1.19.
