### ISSUE TITLE
The editor window isn't resizeable after you've launched a VCV-Host VST editor window

### ISSUE THREAD

**Issue by RichieHindle** [EntrianAudio/Rack#48]
After showing a VCV-Host editor window, subsequent Entrian Sequencers editor windows aren't resizeable.

(The Entrian Sequencers editor doesn't tell GLFW whether to make the window resizeable or not, so GLFW will default the GLFW_RESIZABLE property to be the same as the last window created.  If that was the main Rack window then it will be resizeable, but if it was a VST editor window, it won't.)

**Comment by RichieHindle** [comment]
See also /david-c14/ModularFungi/issues/31 (same chunk of Richie's buggy code ! 😃 ).

**Comment by EntrianAudio** [comment]
Fixed.
