### ISSUE TITLE
Time division by 3 in sequencers

### ISSUE THREAD

**Issue by mhampton** [EntrianAudio/Rack#52]
Maybe I just missed how to do this, but I didn't see a way to subdivide a grid into triplets in the Entrian sequencers.  Adding a %3 option would be really nice.   I can work around it by unquantizing and doing triplets by hand, but its pretty slow.

**Comment by RichieHindle** [comment]
You can set a "Beats per bar" that's a multiple of 3 - does that do what you need?:

![image](https://user-images.githubusercontent.com/4448057/94377325-8066dd80-0118-11eb-9f21-f35aa3673031.png)

**Comment by mhampton** [comment]
I guess I could globally do something like 12 beats per bar.  What I wanted was to be able to put in a triplet phrase within a midi section that was otherwise in 4/4, for example.  As it is, within a melody/midi section you can change the subdivisions by factors of 2, but you can't subdivide by 3.

**Comment by RichieHindle** [comment]
Ah, understood.  You can type whatever number you like into the "Steps per beat" quantization setting - you don't need to use the ÷2 / ×2 buttons.  So you can set it to three steps per beat to enter your triplet:

![image](https://user-images.githubusercontent.com/4448057/94396455-dd36b800-0159-11eb-996a-b148c6c59dd2.png)

**Comment by mhampton** [comment]
Ok that's embarrassing - I don't know why I didn't see that I could do that.  Some kind of brain freeze.  Thanks for taking the time to point that out.

**Comment by EntrianAudio** [comment]
😃  No problem!
