### ISSUE TITLE
Midi rotation feature request for Timeline

### ISSUE THREAD

**Issue by SergeProtectorMusic** [EntrianAudio/Rack#53]
Entrian Timeline assigns new notes to the first free channel. As a result, when using an adsr, notes have no release phase if followed closely by another note. While there's a workaround with reserved channels, it would be great if you added midi rotation to handle this automatically.

Great modules! Thanks for all you do for the VCV community!

**Comment by RichieHindle** [comment]
Good point!  I'll fix that in a future release, and let you know when the fix is available.

**Comment by SergeProtectorMusic** [comment]
Awesome! Thanks so much!

**Comment by EntrianAudio** [comment]
Implemented in version 1.1.19:

![image](https://user-images.githubusercontent.com/61119919/105964731-821ac080-607a-11eb-8d2f-fdc987511196.png)
