### ISSUE TITLE
More options for voltage quantization in CV clips

### ISSUE THREAD

**Issue by EntrianAudio** [EntrianAudio/Rack#6]
Voltages in CV clips are always quantized to 1/12th of a volt.  It would be good to be able to select a more coarse quantization, like 1V.

(Suggestion from forum member jue).

**Comment by RichieHindle** [comment]
You should also be able to drag CV notes to arbitrary voltages with no snapping, and there are other snapping "scales" that would be useful, eg. the BPM scale for Tempo tracks (0V = 120BPM) snapped to the nearest BPM.

**Comment by EntrianAudio** [comment]
Implemented in version 1.1.17.  See the "Snap to" dropdown the editor.
