### ISSUE TITLE
Melody: Number of output channels doesn't change 

### ISSUE THREAD

**Issue by ROGAVKA** [EntrianAudio/Rack#60]
Hi,
having a great time with Melody so far, however more often than not I change the number of channels, press OK and the output cables still carry the old number of channels. I tried reconnecting cables, nothing helps :( If I first select number of channels and then connect cables it seems ok, but it's very annoying since I usually change my decision on the polyphony in the process.
Was using only melody so far, so not sure if the problem persists in other sequencers
Attaching screenshot
![Clipboard01](https://user-images.githubusercontent.com/44550443/99148880-69b22100-269b-11eb-8ccd-071efe0b4ed4.jpg)

**Comment by ROGAVKA** [comment]
I also noted just now that if I use Dynamic mode it seems that the sequencer still rotates over old number of channels. So looks like a bug definitely :(

**Comment by EntrianAudio** [comment]
It used to be the case that Melody clips would always assign the lowest available channel to each note, so the output polyphony of the clip would always be the maximum number of simultaneous dynamic notes plus the count of reserved channels.  The "Melody polyphony" slider put a limit on the output polyphony, but wouldn't change anything if the number of required channels was lower than that limit.

Now, in version 1.1.19, you can tell a Melody track to use *all* the available output channels, rotating the notes between them.  See issue #53.  This sets the output polyphony to the value of the "Melody polyphony" slider directly, regardless of the number of simultaneous notes in the clip.

![image](https://user-images.githubusercontent.com/61119919/105965507-6a900780-607b-11eb-9fc8-3e07a0af30ab.png)
