### ISSUE TITLE
Entrian Sequencers Drummer occasionally misses a beat

### ISSUE THREAD

**Issue by GretchenV63** [EntrianAudio/Rack#67]
I had set up Entrian Sequencers Timeline as shared playlist leader, Entrian Sequencers Drummer as a shared playlist follower. Clock, Reset and Run signals connected to the same small instance of CLKD set at 126 BPM x4. Programmed a 32 beats sequence with 4 steps per beat in both Drummer and Timeline, the Drummer section went to a kick drum (Trummor) and the Timeline to a bass line (evenVCO with Boomsitck) and an organ style thing .

 Programmed a steady 4 on the floor kick drum with a few missing beats in the first 2 bars (of 4 beats) and a rhythmic sequence in the bass line in timeline. 6 other channels in Drummer were doing. The organ was playing a high pitched quintuplet thing for at most three bars (achieved by temporarily switching to 20 steps per beat), then back again to 8 steps per beat for the rest of the song/clip. 

 When playing looped, I noticed that Drummer would occasionally miss a one or two beats, a random one. Muted all the other channels of the drum kit and it stayed. Also in other songs in the same setup (64 and 48 beats).

The sequence is in https://patchstorage.com/vcp-60-this-is-just-a-pop-song/ Select the 'Intro' song. Track 6 is what was in Drummer (which has been removed).

**Comment by RichieHindle** [comment]
Many thanks for the detailed bug report, and the patch.  I've reproduced the problem, and I'll see what I can find.

**Comment by RichieHindle** [comment]
Fixed - thanks again for the bug report.
