### ISSUE TITLE
A way to record in free loop mode ?

### ISSUE THREAD

**Issue by nay-seven** [EntrianAudio/Rack#68]
Hello, just finally buy these modules, really great & useful ! 

now, can't find a way to record ( melody or CV) in a free loop mode
i mean: i want start recording, enter some notes, stop recording and the sequencer loop only what i have recorded
currently the sequencer continue, i need to create the loop manually

a way to do this ?

Thanks

**Comment by RichieHindle** [comment]
One way to do this would be for recording to optionally drop repeat markers when you start and stop recording.  That way, the section of the song that you just recorded would automatically play on a loop after you stopped recording:

![image](https://user-images.githubusercontent.com/4448057/110236820-dd6c8800-7f2f-11eb-975c-4fcb83f6140e.png)

The repeat markers would quantise to the nearest beat.

Would that give you what you're asking for, or have I misunderstood?

**Comment by nay-seven** [comment]
Thanks,
That's the way i use, yes, but needed to be manualy done with the mouse ?
I'm trying to create a complete config with Midi controllers only so
any chance the module create this markers at least the end one when i stop recording ?

**Comment by RichieHindle** [comment]
I mean it would be done automatically, so the first marker would appear automatically when you start recording, and the second marker would appear automatically when you stop recording.  The playhead would then loop between the markers.

You'd enable this behaviour via an option on the right-click menu of the module, something like "Automatically add repeat markers when recording".

**Comment by nay-seven** [comment]
ha yes,  I didn't pay attention to the " would be " ;-) ( sorry English is not my native language)
Yes that would be perfect !!

**Comment by RichieHindle** [comment]
OK, cool.  Leave it with me and I'll see what I can do for a future version.

**Comment by nay-seven** [comment]
hello, any news on this request ? ;-)

**Comment by RichieHindle** [comment]
Yes, good news: this feature will be included in the next version, which is due for release before the end of September.

**Comment by nay-seven** [comment]
cool ! good news, thanks a  lot !

**Comment by EntrianAudio** [comment]
Apologies for how long September turned out to be, but this feature is now implemented.  😄
