### ISSUE TITLE
Timeline & Melody sequencer - notes don't always line up with steps with quantize

### ISSUE THREAD

**Issue by paulpiko** [EntrianAudio/Rack#69]
For example, in Timeline/Melody when using 7 steps per beat and quantise on, the notes do not line up with the steps

![image](https://user-images.githubusercontent.com/56526215/111593209-d3933080-881d-11eb-9f71-fe350168eff8.png)

**Comment by RichieHindle** [comment]
Ouch!  It works fine for "normal" values like 4 or 6, but then fails for 7 and for some even numbers like 10.  Will investigate.

**Comment by RichieHindle** [comment]
Fixed - thanks for the bug report.

(Note that if you zoom right in, the notes might still be slightly off; that's because the sequencers have an internal resolution of 1/96th of a beat, so where the quantisation step doesn't divide into 96, you get a slight rounding error.)
