### ISSUE TITLE
Record sequence in Timeline/Melody without running

### ISSUE THREAD

**Issue by paulpiko** [EntrianAudio/Rack#70]
Hi! For those of us who are uncoordinated, I'd like an option to record a note, e.g. from a midi keyboard, and have the play/record head move forward a step, ready for the next note. I don't want the record head continually advancing without input.

And even better would be including way to indicate a rest/skip a step 🙂

P.S.: I was reminded of this after watching this Ableton video https://youtu.be/ecP_l-ySk4E

**Comment by RichieHindle** [comment]
Nice idea!  Here are a few more details - let me know whether they make sense:

* Step Recording is active when Record is enabled but Run is not enabled, which (I think!) was kind of a meaningless state before.
* The playhead moves forward by the quantisation step, so if you're quantising to two steps per beat, you add notes that are half a beat apart.
* The length of each note is the same as the amount by which the playhead moves, so they fill the space.
* To add a rest, ensure your mouse cursor is hovering over the module and press the spacebar.
* Recording adds to what's there, so you can build polyphonic sequences by going over them multiple times.
* It works for Melody clips and Drum clips, but not CV clips.

Will that do what you're asking for?

**Comment by paulpiko** [comment]
That sounds good! Thanks!

**Comment by RichieHindle** [comment]
Done - thanks for the suggestion!
