### ISSUE TITLE
Kick won’t map

### ISSUE THREAD

**Issue by PatchworkBoy** [EntrianAudio/Rack#71]
Hi - Acoustic Drummer Sequencer (commercial version) - have a Roland HD1 hooked up... sequencer captures everything BUT the kickdrum.

Attempted playing in all notes from C1 thru C3 using Entrian Melody into Drum Seq, but no kick drum is ever captured. What MIDI Note is the drum sequencer listening for for Kick?? (Everything else on the HD1 V-drum kit maps PERFECTLY)

**Comment by PatchworkBoy** [comment]
Ps: kick recorded into Melody is coming thru as C1...

**Comment by RichieHindle** [comment]
It listens for both **B0, Note 35, Acoustic Bass Drum** and **C1, Note 36, Bass Drum 1**.

Bear in mind that Rack and General MIDI using different naming conventions for note numbers, so what the MIDI standard calls C1, Rack calls C2.  Annoying but true.  It's odd that recording into Melody would show up as C1 when the other instruments work...!

Just in case, can I check that you're sending your input to the "GMIDI" input, and that you don't have anything plugged into the "C4-E5" input, and that you've also wired up the Trigger input, as shown in the screenshot below?

For me, recording a (Rack) C2 from Melody into Drummer captures a note on Channel 1:

![image](https://user-images.githubusercontent.com/4448057/112767299-d8ba6180-900d-11eb-81a8-01230696e3db.png)

**Comment by PatchworkBoy** [comment]
Closing - unsure what happened last night... fired same patch up this morning and it’s picking it up perfectly now. *shrug* Sorry!

**Comment by RichieHindle** [comment]
Bizarre... if it ever happens again and you're able to figure out what was going on, I'd love to know!
