### ISSUE TITLE
Entrian Drummer - crash on exit

### ISSUE THREAD

**Issue by dheles** [EntrianAudio/Rack#73]
When I quit VCV Rack after using Entrain Drummer in a patch, Rack hangs on exit, requiring me to force quit the application. I can reliably reproduce this using a patch which contains only Entrain Drummer, and no other modules. The problem persists for the next exit after I remove ED, but then goes away until I add ED back into a patch. Attached is the VCV Rack log and the patch file. I can also share the crash report from the OS with you privately as well, if that would be helpful.

Intel MacBook Pro
MacOS 10.14.6 Mojave

[log_ed.txt](https://github.com/EntrianAudio/Rack/files/6331207/log_ed.txt)
[ed.txt](https://github.com/EntrianAudio/Rack/files/6331210/ed.txt)

**Comment by RichieHindle** [comment]
Thanks for the detailed bug report, and the patch.  Sadly I can't reproduce the crash here (and I haven't any any similar reports from other users).

Can I ask, do you have to show Drummer's editor window for the hang to happen, or is it enough just have Drummer in the patch?  If you do need to show the editor, does the same problem happen with other modules that show popup windows, for example Modular Fungi Opsylloscope?

**Comment by EntrianAudio** [comment]
Fixed.
