### ISSUE TITLE
Version for Rack V2 ?

### ISSUE THREAD

**Issue by nay-seven** [EntrianAudio/Rack#84]
Hello, i have your modules in Pro version, can we except a new version for Rack v2 please ?
Thanks

**Comment by RichieHindle** [comment]
Yes, absolutely!  It's on its way. and I'm hoping to have it released this week.

**Comment by nay-seven** [comment]
Great, Thanks a lot !

**Comment by EntrianAudio** [comment]
All the Entrian plugins are now in the VCV Library for Rack V2.
