### ISSUE TITLE
Timeline note position and quantisation issues

### ISSUE THREAD

**Issue by paulpiko** [EntrianAudio/Rack#85]
In Timeline 2.1.24, the note position and quantisation can be off when using an unusual step setting.

In this image, the notes placed do not line up on the grid, and do not fill the column.

![image](https://user-images.githubusercontent.com/56526215/149610047-7dbfd4b2-9ed9-49c1-a993-34fee0c4c557.png)

Quantise all notes does not result in a consistent length too, see the 6th note is shorter while others are longer than a step, and notes are not aligned with grid.

![image](https://user-images.githubusercontent.com/56526215/149610027-26ca6dcc-096b-4d7d-bd05-49c5b6c1db29.png)

**Comment by RichieHindle** [comment]
Hi Paul,

Note positions and lengths are stored with an accuracy of 1/96th of a beat.

By quantising to 1/14ths of a beat, you'll see a slight misalignment: for example, a note at 4/14ths of a beat will be rounded to 14/96ths, which is off by about 0.44% of a beat.

You can see that in a zoomed-in editor: if your editor is 1000px per beat, the note will be off by 4px.  But given that in audio terms it's about 2ms (at 120BPM), you'd be hard pressed to hear the difference!

**Comment by paulpiko** [comment]
Thanks, that's fair enough. I was throwing weird stuff at it ;-)

**Comment by EntrianAudio** [comment]
:+1:
