### ISSUE TITLE
Pitch follower not working (with engine sample rates lower than 44.1kHz)

### ISSUE THREAD

**Issue by yellowmastodon** [EntrianAudio/Rack#90]
The pitch follower is not showing or sending any values.
It generates high CPU load.
When I try to delete it or start a new patch it freezes VCV Rack.
I do not know if there is a way to retrieve some error log, except log.txt (nothing there), but if you point me in the right direction I can supply it. 

OS: Windows 10
Plugin version: 2.1.25
Tested with Rack versions: 2.0.0, 2.1.1 2.3.0 (all encountering the same problem)

![image](https://github.com/EntrianAudio/Rack/assets/133022891/5903a8ce-50df-42bb-8992-89d227ca5506)

**Comment by yellowmastodon** [comment]
Progress in debugging:

The problem seems to occur only on Engine Sample rates lower than 44.1kHz.
If I set the Sample Rate to 44.1kHz and up, then restart Rack, it begins to work.
(actually I needed to stop rack from task manager, start new patch, set the sample rate and then restart, as the setting was not getting saved)

This seems somehow understandable to me, when processing audio to determine pitch. But maybe some workaround could be implemented - module gets into bypass mode, when lower engine sample rate is set and notifies the user to change it?

**Comment by RichieHindle** [comment]
Thank you for the analysis!  I'll look into it and see whether it can made to work, or if not, at least to fail gracefully.  In theory there's no reason it shouldn't work at any sample rate - the only difference ought to be the latency.

**Comment by RichieHindle** [comment]
Fixed in version 2.2.0 - sorry it's taken so long...
